"""add user_id to physical_devices

Revision ID: 1701e4400cb5
Revises: 1605e4400cb4
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1701e4400cb5'
down_revision: Union[str, None] = '1605e4400cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, add the user_id column as nullable
    op.add_column('physical_devices', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Create a temporary user for existing devices (this should be replaced with actual user logic)
    # For now, we'll use a placeholder UUID - in production, you'd want to handle this differently
    temp_user_id = '00000000-0000-0000-0000-000000000000'
    
    # Update existing records with the temporary user_id
    op.execute(f"UPDATE physical_devices SET user_id = '{temp_user_id}' WHERE user_id IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('physical_devices', 'user_id', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('physical_devices', 'user_id')
    # ### end Alembic commands ###
